### ISSUE TITLE
Block-autoplay experiment is not removed after its expiration date

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [alastor0325/autoplay-shield-study#10] opened 2018-09-24 15:27 UTC
**[Affected versions]:**
- Firefox Beta Unbranded 63.0b8

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
      - shieldStudy.logLevel to All;
      - extensions.fastblock_shield_mozilla_org.test.variationName to one of the following values: control, block, allow-and-remember or allow-and-notRemember;
      - extensions.legacy.enabled to true;
      - xpinstall.signatures.required to false.
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Set the system date to 2 weeks after the current date.
2. Open the browser with the profile from prerequisites and navigate to "about:addons">Extensions section.
3. Observe the add-ons section.

**[Expected result]:**
- Block-autoplay experiment is uninstalled and no longer displayed in the add-ons section.

**[Actual result]:**
- Block-autoplay experiment remains installed and displayed in the add-ons section.

**[Notes]:**
- The "Exit" and "Expired" telemetry pings are generated and displayed in "about:telemetry" page.
- Added a screen recording the issue:

![expire](https://user-images.githubusercontent.com/40061643/45961440-2f064e00-c027-11e8-9c74-4cf4ba5d099b.gif)

**Comment by alastor0325** [comment] 2018-09-24 20:34
I've committed https://github.com/alastor0325/autoplay-shield-study/pull/3/commits/04f58a1ab2102a5d1f9d8117ec719f8098e41278 and https://github.com/alastor0325/autoplay-shield-study/pull/3/commits/a49276bd708480bc2dd447b3373d6d2fc264593e to ensure we would clean up all stuff and uninstall itself when the study ends.

However, the uninstalling process couldn't be tested on `about:addon`, because the uninstalling process of shield-study addons is different with the process of normal addons. For normal add-ons, we use `addon manager` to uninstall them which won’t give addons any time to do clean-up when uninstalling them.

That is the reason why uninstallation would fail on this bug, because the extension had been destroyed before we called `cleanup()`, and then it results in errors in `cleanup()` so that we can't uninstall the addon correctly.

However, in a real situation, we would uninstall shield-study addons by Normandy, which would give shield-study addons enough time to do `clearup()` before uninstallation.

**Closed as completed by alastor0325** 2018-09-24 20:34 UTC

**Comment by alastor0325** [comment] 2018-09-24 20:36
In addition, I've asked the shield-study team, they told me that now they didn't have any way to test the uninstalling process of shield study...

**Comment by Softvision-RemusDranca** [comment] 2018-09-26 16:08
Our concern is that there is the possibility of Normandy failing on the study expiry step, since we don't have any control over this. If possible, we think it would be better for everyone to implement an expiry date based on the installation time as a fail safe mechanism. 
These dual checks were already implemented on most of the studies tested by the team until now and worked perfectly.

However, if you guys don't see this as a problem / risk, please let us know so we won't invest any testing time on this part.

**Comment by alastor0325** [comment] 2018-09-27 00:26
@Softvision-RemusDranca Ah, I think I found where the problem is, it's fixed by https://github.com/alastor0325/autoplay-shield-study/commit/74228dae8a668caa0d19c93cb16085fe01018e9e.

Thank you!

**Comment by Softvision-RemusDranca** [comment] 2018-09-27 13:56
I have verified this issue using the latest Block Autoplay (2.0.0) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
Thank you for fixing this!
